application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000

mail:
  host: smtp.gmail.com
  port: 587
  username: levantrang.forwork@gmail.com
  password: iktvyqeiptjuunwd
  properties:
    mail:
      smtp:
        auth: true

        starttls:
          enable: true
