create table orders
(
    id serial primary key,
    customer_id int,
    recipient_name varchar(100),
    recipient_phone varchar(100),
    recipient_email varchar(100),
    address varchar(200),
    total_money float,
    ship_fee float,
    goods_value float,
    checkout float,
    quantity int,
    ship_date timestamp,
    carrier varchar(100),
    ctime timestamp  DEFAULT current_timestamp ,
    mtime timestamp  DEFAULT NULL,
    pay_status int,
    order_status int,
    note text,
    cancel_note text,
    delivery int,
    purchaseType int,
    constraint fk_customers FOREIGN KEY (customer_id) REFERENCES customers(id)
);
